// Small fixed symbol tables used by autocomplete + the math symbol palette.

export const LATEX_COMMANDS: Array<{ label: string; detail: string; apply?: string }> = [
  { label: "\\textbf", detail: "bold text", apply: "\\textbf{}" },
  { label: "\\textit", detail: "italic text", apply: "\\textit{}" },
  { label: "\\underline", detail: "underline text", apply: "\\underline{}" },
  { label: "\\emph", detail: "emphasized text", apply: "\\emph{}" },
  { label: "\\section", detail: "section heading", apply: "\\section{}" },
  { label: "\\subsection", detail: "subsection heading", apply: "\\subsection{}" },
  { label: "\\subsubsection", detail: "subsubsection heading", apply: "\\subsubsection{}" },
  { label: "\\chapter", detail: "chapter heading", apply: "\\chapter{}" },
  { label: "\\paragraph", detail: "paragraph heading", apply: "\\paragraph{}" },
  { label: "\\label", detail: "define a label", apply: "\\label{}" },
  { label: "\\ref", detail: "reference a label", apply: "\\ref{}" },
  { label: "\\eqref", detail: "reference an equation", apply: "\\eqref{}" },
  { label: "\\cite", detail: "cite a bibliography key", apply: "\\cite{}" },
  { label: "\\citep", detail: "parenthetical citation", apply: "\\citep{}" },
  { label: "\\citet", detail: "textual citation", apply: "\\citet{}" },
  { label: "\\footnote", detail: "insert footnote", apply: "\\footnote{}" },
  { label: "\\includegraphics", detail: "insert image", apply: "\\includegraphics[width=\\linewidth]{}" },
  { label: "\\include", detail: "include a file", apply: "\\include{}" },
  { label: "\\input", detail: "input a file", apply: "\\input{}" },
  { label: "\\usepackage", detail: "load a package", apply: "\\usepackage{}" },
  { label: "\\documentclass", detail: "document class", apply: "\\documentclass{}" },
  { label: "\\begin", detail: "begin an environment", apply: "\\begin{}" },
  { label: "\\end", detail: "end an environment", apply: "\\end{}" },
  { label: "\\item", detail: "list item" },
  { label: "\\frac", detail: "fraction", apply: "\\frac{}{}" },
  { label: "\\sqrt", detail: "square root", apply: "\\sqrt{}" },
  { label: "\\sum", detail: "summation" },
  { label: "\\int", detail: "integral" },
  { label: "\\alpha", detail: "Greek letter alpha" },
  { label: "\\beta", detail: "Greek letter beta" },
  { label: "\\caption", detail: "figure/table caption", apply: "\\caption{}" },
  { label: "\\maketitle", detail: "render title block" },
  { label: "\\tableofcontents", detail: "insert table of contents" },
  { label: "\\newcommand", detail: "define a new command", apply: "\\newcommand{}{}" },
];

export const LATEX_ENVIRONMENTS = [
  "document",
  "equation",
  "equation*",
  "align",
  "align*",
  "figure",
  "table",
  "tabular",
  "itemize",
  "enumerate",
  "description",
  "abstract",
  "quote",
  "verbatim",
  "center",
  "matrix",
  "pmatrix",
  "bmatrix",
  "theorem",
  "proof",
  "minipage",
];

export const LATEX_PACKAGES = [
  "amsmath",
  "amssymb",
  "amsthm",
  "graphicx",
  "hyperref",
  "geometry",
  "babel",
  "inputenc",
  "fontenc",
  "biblatex",
  "natbib",
  "booktabs",
  "xcolor",
  "listings",
  "algorithm",
  "algorithmic",
  "tikz",
  "caption",
  "subcaption",
  "float",
  "multirow",
  "siunitx",
  "cleveref",
  "minted",
];

export interface MathSymbol {
  label: string;
  insert: string;
  category: "Greek" | "Operators" | "Relations" | "Arrows" | "Misc";
}

export const MATH_SYMBOLS: MathSymbol[] = [
  { label: "\\alpha", insert: "\\alpha", category: "Greek" },
  { label: "\\beta", insert: "\\beta", category: "Greek" },
  { label: "\\gamma", insert: "\\gamma", category: "Greek" },
  { label: "\\delta", insert: "\\delta", category: "Greek" },
  { label: "\\epsilon", insert: "\\epsilon", category: "Greek" },
  { label: "\\theta", insert: "\\theta", category: "Greek" },
  { label: "\\lambda", insert: "\\lambda", category: "Greek" },
  { label: "\\mu", insert: "\\mu", category: "Greek" },
  { label: "\\pi", insert: "\\pi", category: "Greek" },
  { label: "\\sigma", insert: "\\sigma", category: "Greek" },
  { label: "\\phi", insert: "\\phi", category: "Greek" },
  { label: "\\omega", insert: "\\omega", category: "Greek" },
  { label: "\\Sigma", insert: "\\Sigma", category: "Greek" },
  { label: "\\Omega", insert: "\\Omega", category: "Greek" },
  { label: "\\sum", insert: "\\sum_{}^{}", category: "Operators" },
  { label: "\\int", insert: "\\int_{}^{}", category: "Operators" },
  { label: "\\prod", insert: "\\prod_{}^{}", category: "Operators" },
  { label: "\\frac{}{}", insert: "\\frac{}{}", category: "Operators" },
  { label: "\\sqrt{}", insert: "\\sqrt{}", category: "Operators" },
  { label: "\\partial", insert: "\\partial", category: "Operators" },
  { label: "\\nabla", insert: "\\nabla", category: "Operators" },
  { label: "\\infty", insert: "\\infty", category: "Misc" },
  { label: "\\leq", insert: "\\leq", category: "Relations" },
  { label: "\\geq", insert: "\\geq", category: "Relations" },
  { label: "\\neq", insert: "\\neq", category: "Relations" },
  { label: "\\approx", insert: "\\approx", category: "Relations" },
  { label: "\\equiv", insert: "\\equiv", category: "Relations" },
  { label: "\\in", insert: "\\in", category: "Relations" },
  { label: "\\subset", insert: "\\subset", category: "Relations" },
  { label: "\\rightarrow", insert: "\\rightarrow", category: "Arrows" },
  { label: "\\leftarrow", insert: "\\leftarrow", category: "Arrows" },
  { label: "\\Rightarrow", insert: "\\Rightarrow", category: "Arrows" },
  { label: "\\leftrightarrow", insert: "\\leftrightarrow", category: "Arrows" },
  { label: "\\cdot", insert: "\\cdot", category: "Misc" },
  { label: "\\times", insert: "\\times", category: "Misc" },
  { label: "\\pm", insert: "\\pm", category: "Misc" },
  { label: "\\forall", insert: "\\forall", category: "Misc" },
  { label: "\\exists", insert: "\\exists", category: "Misc" },
];
